name: generate-snake-game-from-github-contribution-grid

on:
  workflow_dispatch: # This triggers the workflow manually, but you can adjust it to your needs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: thauanb
          palette: github-dark
          color_snake: blue
          color_dots: #bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Publish Snake Game
        run: |
          mv dark.svg?palette=github-dark&color_snake=blue dark.svg
          mv light.svg?color_snake=#7845ab light.svg
          mv ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9 ocean.gif
        working-directory: ${{ github.workspace }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: snake-game
          path: ./
